AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
# Details about Lambda2 function
  LF2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      FunctionName: search-photos
      Role: arn:aws:iam::764420359320:role/lf1-role-assigment-2
      CodeUri: ./lf2/
      Timeout: 30




